version: "3.4"

services:
  piptools:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: piptools
    volumes:
      - .:/app:z

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - .:/app:z
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres

  postgres:
    image: "postgres:13-alpine"
    volumes:
      -  db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=invoicing
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

volumes:
  db_data:
