tag-pattern: &tag-pattern
  only: /^\d+\.\d+\.\d+(\.\d)*$/

version: 2.1

jobs:
  tests:
    docker:
      - image: circleci/python:3.9
        environment:
          - ALLOWED_HOSTS: localhost
          - SECRET_KEY: a-secret-that-must-not-be-shared-with-anyone-else-because-it-is-really-important
          - COVERALLS_FLAG_NAME: "tests"
          - DATABASE_URL: postgres://postgres@localhost/invoicing

      - image: circleci/postgres:13.1
        environment:
          - POSTGRES_USER: postgres
          - POSTGRES_DB: invoicing
          - POSTGRES_HOST_AUTH_METHOD: trust


    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "requirements-dev.txt" }}

      - run:
          name: install dependencies
          command: |
            python -m venv .venv
            ./.venv/bin/pip install -U pip pip-tools setuptools awscli
            ./.venv/bin/pip-sync requirements-dev.txt

      - save_cache:
          paths:
            - .venv
          key: v3-dependencies-{{ checksum "requirements-dev.txt" }}

      - run:
          name: run tests
          command: |
            ./.venv/bin/pytest -n 2

      - store_test_results:
          path: build

      - run:
          name: upload coverage
          command: |
            ./.venv/bin/coveralls

workflows:
  version: 2
  main:
    jobs:
      - tests:
          filters:
            tags:
              <<: *tag-pattern