# Generated by Django 3.1.7 on 2021-04-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210409_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketable',
            name='kind',
            field=models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], default='PRODUCT', max_length=1024, verbose_name='Kind'),
        ),
    ]
