# Generated by Django 3.1.7 on 2021-04-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210410_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='kind',
            field=models.CharField(blank=True, choices=[('PERSON', 'Person'), ('ORGANIZATION', 'Organization')], default='ORGANIZATION', max_length=1024, verbose_name='Kind'),
        ),
    ]
